version: '3.1'

services:
  redis:
    image: redis
    ports: ['6379:6379']
    healthcheck:
      test: ["CMD", "redis-cli","ping"]

  postgres:
    image: postgres:16
    ports: ['5432:5432']
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: app_development
      POSTGRES_PASSWORD: secret
    volumes:
    - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "app", "-d", "app_development"]
      interval: 1s
      retries: 5

  base: &base
    depends_on: ["redis", "postgres"]
    restart: on-failure:3
    tty: true
    build:
      context: .
      target: development
    environment:
      - REDIS_URL=redis://redis/0
      - DATABASE_URL=postgres://app:secret@postgres/app_development
    ports: ["3000:3000"]
    volumes:
      - .:/rails

  worker:
    <<: *base
    restart: on-failure:3
    tty: false
    ports: []
    command: bin/rails solid_queue:start

volumes:
  pgdata:
