databases:
  - name: hostedgpt
    databaseName: hostedgpt
    user: hostedgpt
    plan: free

envVarGroups:
- name: hostedgpt-secrets
  envVars:
    - key: SECRET_KEY_BASE
      generateValue: true

services:
  - type: web
    name: hostedgpt
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hostedgpt
          property: connectionString
      - fromGroup: hostedgpt-secrets
      - key: RUN_SOLID_QUEUE_IN_PUMA
        value: true
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
