databases:
  - name: hostedgpt
    databaseName: hostedgpt
    user: hostedgpt
    plan: free

services:
  - type: worker
    name: soliqueue-worker
    runtime: ruby
    plan: free
    buildCommand: bundle install
    startCommand: ./bin/rake solid_queue:start 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hostedgpt
          property: connectionString
      - key: RAILS_MASTER_KEY
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
        sync: false
  - type: web
    name: hostedgpt
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hostedgpt
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
