databases:
  - name: hostedgpt-postgres
    databaseName: hostedgpt
    user: hostedgpt
    plan: free

envVarGroups:
- name: hostedgpt-secrets
  envVars:
    - key: SECRET_KEY_BASE
      generateValue: true

services:
  - type: web
    name: hostedgpt
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hostedgpt-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: hostedgpt-redis
          property: connectionString
      - fromGroup: hostedgpt-secrets
      - key: RUN_SOLID_QUEUE_IN_PUMA
        value: true
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
  - type: redis
    plan: free
    name: hostedgpt-redis
    ipAllowList: [] # no external connections
